config/routes.rb
Rails.application.routes.draw do
  
  #root 'dashboard#show'

  get 'users/new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :sessions, only: [:create]
  resources :users, only: [:new, :create, :index, :edit, :show]
  
resources :users do
    resources :posts
end


resources :users do
	get ':user_name', to: 'profiles#show', as: :profile
end

resources :posts
root  'posts#index'

resources :posts do
  resources :comments
end

get 'profiles/show'
get ':user_name', to: 'profiles#show', as: :profile
get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
patch ':user_name/edit', to: 'profiles#update', as: :update_profile

resources :search, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :user_id, presence: true
	validates :image, presence: true
	mount_uploader :image, ImageUploader
	belongs_to :user
	has_many :comments, dependent: :destroy
	#include PgSearch
  #pg_search_scope :search_by_caption, against: [:caption], using: {
      #tsearch: {
        #prefix: true
      #}
    #}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true, presence: true
  validates :user_name, presence: true, length: { minimum: 2, maximum: 16 }
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  include PgSearch
  pg_search_scope :search, against: [:user_name], using: {
      tsearch: {
        prefix: true
      }
    }

  enum role: [:user, :admin, :god]
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :require_valid_user!

  def current_user
    if !session[:user_id].blank?
      @user ||= User.find(session[:user_id])
    end
  end

  def require_valid_user!
    if current_user.nil?
      flash[:error] = 'You must be logged in to access that page!'
      redirect_to login_path
    end
  end

  private

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :set_post

def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Check the comment form, something went wrong."
      render root_path
    end
  end

private

def comment_params
  params.require(:comment).permit(:content)
end

def set_post
  @post = Post.find(params[:post_id])
end

def destroy
  @comment = @post.comments.find(params[:id])

  @comment.destroy
  flash[:success] = "Comment deleted :("
  redirect_to root_path
end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :owned_post, only: [:edit, :update, :destroy]

def index
	@posts = Post.all
end

def new
	@post = Post.new
end

def create
    @post = Post.new(post_params)
    @post['user_id'] = current_user.id
    if @post.save
      flash[:success] = "Your post has been created."
      redirect_to posts_path
    else
      flash[:alert] = "Your post was not created! Please check the form and try again."
      render :new
    end
end

def show
  @post = Post.find(params[:id])
end

def edit
	@post = Post.find(params[:id])
  
end

def update
  if @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to(post_path(@post))
    flash[:success] = "Post updated."
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
end



def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to root_path
end
  
private

def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :user_name, :avatar, :bio)
  end
  
def post_params
    params.require(:post).permit(:caption, :image, :user)
end

def set_post
    @post = Post.find(params[:id])
end







end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 before_action :owned_profile, only: [:edit, :update] 
 before_action :set_user

  def show
  @user = User.find_by(user_name: params[:user_name])
  @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at desc')
  end

def edit
  @user = User.find_by(user_name: params[:user_name])
end

def update
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

private

def profile_params
  params.require(:user).permit(:avatar, :bio)
end

def owned_profile
    @user = User.find_by(user_name: params[:user_name])
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
 end

def set_user
  @user = User.find_by(user_name: params[:user_name])
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_valid_user!, except: [:destroy]

  def new
  end

  def create
    reset_session
    @user = User.find_by(email: session_params[:email])

    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Welcome back!'
      redirect_to root_path
    else
      flash[:error] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end

  def destroy
    reset_session
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_valid_user!
  before_action :authorize_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] =  'You have successfully created an account.  Please sign in to continue.'
      redirect_to login_path
    else
      render :new
    end
  end

  

def index
 #@users = User.all
 @user = User.find_by(user_name: params[:user_name])

 @users = if params[:term]
  User.search(params[:term])
else
  User.all
end
end

def destroy
    User.find_by(user_name: params[:user_name]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :user_name, :avatar, :bio, :term)
  end
end

def authorize_admin
    redirect_to root_path, alert: "Permissions denied" unless
     current_user.admin?
end

app/helpers/application_helper.rb
module ApplicationHelper

	def alert_for(flash_type)
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end



end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="user-name">
  <%= comment.user.user_name %>
  <div class="comment-content"></div>
  <%= comment.content %>
  <% if comment.user == current_user %>
    
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/dashboard/show.html.erb
<h1>Dashboard</h1>
<p>Welcome to your dashboard.</p>




<% if flash[:success] %>
  <%= flash[:success] %>
<% end %>

<%= link_to 'Click here to log out.', logout_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Photogram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
  
</ul>

    </div>
  </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand">
    <%= link_to "Photogram", root_path %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Printstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Printstagram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user %>
        <li>
          <%= link_to "New Post", new_post_path %>
        </li>
        <li>
         <%= link_to 'Click here to log out.', logout_path %> 
       </li>
       
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to 'About', page_path('about') %>
        </li>

       <% else %>
        <li>
          <%= link_to "Login", login_path %>
        </li>
        <li>
          <%= link_to "Register", new_user_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>
  
</div>



    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h2> We are located in the heart of TTDI </h2>
<p>Please click on the map below for a link on Google Maps </p>

<a href="https://www.google.com/maps/place/next+academy/"><img src="https://maps.googleapis.com/maps/api/staticmap?center=next+academy&zoom=17&scale=1&size=600x600&maptype=roadmap&key=AIzaSyD58f65OiH2jwS1NmcIpZbZZ4GbGMzR6IE&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:%7Cnext+academy&signature=JVSu7F13kYGd6qfa8B6lE2vmOW4=" alt="Google Map of next academy"></a>

app/views/posts/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url, class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
  <div class="caption">
    <div class="caption-content">
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
      <%= post.caption %>
    </div>
    <div class="comments" id="comments_<%= post.id %>">
      <% if post.comments %>
        <%= render post.comments, post: post %>
      <% end %>
    </div>
  </div>
</div>
  <div class="comment-like-form row">
 
  <div class="comment-form col-sm-11">
    <%= form_for([post, post.comments.build], remote: true) do |f| %>
      <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
    <% end %>
  </div>
</div>
    
      
      
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
<%= link_to "Cancel", root_path(@post) %>

<div class="text-center">
  <%= image_tag @post.image.url %>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<% if current_user.god? %>
  <h3>Welcome, God.</h3>
<% elsif current_user.admin? %>
  <h3>Welcome, Admin.</h3>
<% else %>
  <h3>Welcome</h3>
<% end %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>


<%= link_to "New Post", new_post_path %>
<%= link_to 'Click here to log out.', logout_path %>

app/views/posts/new.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        <%= @post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url %>
    </div>
    <p class="caption">
      <%= @post.caption %>
    </p>
    <div class="text-center">
      <% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", root_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
    <% else %>
  <div class="text-center edit-links">
    <%= link_to "Back", root_path(@post) %>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path %>
              
            
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      
    </div>
  </div>
</div>




<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/users/index.html.erb
<h2> All Users</h2>

<%= form_tag users_path, method: :get do %>
  <%= text_field_tag 'term', params[:term], placeholder: "Enter username" %>
  <%= submit_tag 'Search' %>
<% end %>



<ul class="users">
  <% @users.each do |user| %>
    <li>
       <%= link_to user.user_name, profile_path(user.user_name) %> 
        
        
    </li>
  <% end %>
</ul>

<%= link_to "Cancel", root_path(@post) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Create a new account using the form below.  All fields are required.</p>

<% if @user.errors.any? %>
  <div class='alert alert-danger'>
    <p>Please correct the following errors:</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <div class='form-group'>

    <%= f.label :user_name %>
    <%= f.text_field :user_name, required: true %>
  </div>

  <div class='form-group'>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit 'Register', class: 'btn btn-primary' %>
<% end %>

<p class='mt-2'>
  Already have an account? <%= link_to 'Click here to sign in.', login_path %>
</p>